package com.anywide.shop.user.entity;

import java.math.BigDecimal;

public class GoldInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gold_info.gold_info_id
     *
     * @mbg.generated Thu Jul 29 19:06:14 CST 2021
     */
    private Integer goldInfoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gold_info.user_id
     *
     * @mbg.generated Thu Jul 29 19:06:14 CST 2021
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gold_info.global_tx_id
     *
     * @mbg.generated Thu Jul 29 19:06:14 CST 2021
     */
    private String globalTxId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gold_info.branch_tx_id
     *
     * @mbg.generated Thu Jul 29 19:06:14 CST 2021
     */
    private String branchTxId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gold_info.status
     *
     * @mbg.generated Thu Jul 29 19:06:14 CST 2021
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gold_info.addtime
     *
     * @mbg.generated Thu Jul 29 19:06:14 CST 2021
     */
    private Integer addtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gold_info.amount
     *
     * @mbg.generated Thu Jul 29 19:06:14 CST 2021
     */
    private BigDecimal amount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gold_info.gold_info_id
     *
     * @return the value of t_gold_info.gold_info_id
     *
     * @mbg.generated Thu Jul 29 19:06:14 CST 2021
     */
    public Integer getGoldInfoId() {
        return goldInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gold_info.gold_info_id
     *
     * @param goldInfoId the value for t_gold_info.gold_info_id
     *
     * @mbg.generated Thu Jul 29 19:06:14 CST 2021
     */
    public void setGoldInfoId(Integer goldInfoId) {
        this.goldInfoId = goldInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gold_info.user_id
     *
     * @return the value of t_gold_info.user_id
     *
     * @mbg.generated Thu Jul 29 19:06:14 CST 2021
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gold_info.user_id
     *
     * @param userId the value for t_gold_info.user_id
     *
     * @mbg.generated Thu Jul 29 19:06:14 CST 2021
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gold_info.global_tx_id
     *
     * @return the value of t_gold_info.global_tx_id
     *
     * @mbg.generated Thu Jul 29 19:06:14 CST 2021
     */
    public String getGlobalTxId() {
        return globalTxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gold_info.global_tx_id
     *
     * @param globalTxId the value for t_gold_info.global_tx_id
     *
     * @mbg.generated Thu Jul 29 19:06:14 CST 2021
     */
    public void setGlobalTxId(String globalTxId) {
        this.globalTxId = globalTxId == null ? null : globalTxId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gold_info.branch_tx_id
     *
     * @return the value of t_gold_info.branch_tx_id
     *
     * @mbg.generated Thu Jul 29 19:06:14 CST 2021
     */
    public String getBranchTxId() {
        return branchTxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gold_info.branch_tx_id
     *
     * @param branchTxId the value for t_gold_info.branch_tx_id
     *
     * @mbg.generated Thu Jul 29 19:06:14 CST 2021
     */
    public void setBranchTxId(String branchTxId) {
        this.branchTxId = branchTxId == null ? null : branchTxId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gold_info.status
     *
     * @return the value of t_gold_info.status
     *
     * @mbg.generated Thu Jul 29 19:06:14 CST 2021
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gold_info.status
     *
     * @param status the value for t_gold_info.status
     *
     * @mbg.generated Thu Jul 29 19:06:14 CST 2021
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gold_info.addtime
     *
     * @return the value of t_gold_info.addtime
     *
     * @mbg.generated Thu Jul 29 19:06:14 CST 2021
     */
    public Integer getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gold_info.addtime
     *
     * @param addtime the value for t_gold_info.addtime
     *
     * @mbg.generated Thu Jul 29 19:06:14 CST 2021
     */
    public void setAddtime(Integer addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gold_info.amount
     *
     * @return the value of t_gold_info.amount
     *
     * @mbg.generated Thu Jul 29 19:06:14 CST 2021
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gold_info.amount
     *
     * @param amount the value for t_gold_info.amount
     *
     * @mbg.generated Thu Jul 29 19:06:14 CST 2021
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }
}