package com.anywide.shop.user.entity;

import java.math.BigDecimal;

public class User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.user_id
	 * @mbg.generated  Thu Jul 29 19:06:14 CST 2021
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.username
	 * @mbg.generated  Thu Jul 29 19:06:14 CST 2021
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.password
	 * @mbg.generated  Thu Jul 29 19:06:14 CST 2021
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.addtime
	 * @mbg.generated  Thu Jul 29 19:06:14 CST 2021
	 */
	private Integer addtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.lastlogin
	 * @mbg.generated  Thu Jul 29 19:06:14 CST 2021
	 */
	private Integer lastlogin;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.gold
	 * @mbg.generated  Thu Jul 29 19:06:14 CST 2021
	 */
	private BigDecimal gold;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.user_id
	 * @return  the value of t_user.user_id
	 * @mbg.generated  Thu Jul 29 19:06:14 CST 2021
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.user_id
	 * @param userId  the value for t_user.user_id
	 * @mbg.generated  Thu Jul 29 19:06:14 CST 2021
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.username
	 * @return  the value of t_user.username
	 * @mbg.generated  Thu Jul 29 19:06:14 CST 2021
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.username
	 * @param username  the value for t_user.username
	 * @mbg.generated  Thu Jul 29 19:06:14 CST 2021
	 */
	public void setUsername(String username) {
		this.username = username == null ? null : username.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.password
	 * @return  the value of t_user.password
	 * @mbg.generated  Thu Jul 29 19:06:14 CST 2021
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.password
	 * @param password  the value for t_user.password
	 * @mbg.generated  Thu Jul 29 19:06:14 CST 2021
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.addtime
	 * @return  the value of t_user.addtime
	 * @mbg.generated  Thu Jul 29 19:06:14 CST 2021
	 */
	public Integer getAddtime() {
		return addtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.addtime
	 * @param addtime  the value for t_user.addtime
	 * @mbg.generated  Thu Jul 29 19:06:14 CST 2021
	 */
	public void setAddtime(Integer addtime) {
		this.addtime = addtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.lastlogin
	 * @return  the value of t_user.lastlogin
	 * @mbg.generated  Thu Jul 29 19:06:14 CST 2021
	 */
	public Integer getLastlogin() {
		return lastlogin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.lastlogin
	 * @param lastlogin  the value for t_user.lastlogin
	 * @mbg.generated  Thu Jul 29 19:06:14 CST 2021
	 */
	public void setLastlogin(Integer lastlogin) {
		this.lastlogin = lastlogin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.gold
	 * @return  the value of t_user.gold
	 * @mbg.generated  Thu Jul 29 19:06:14 CST 2021
	 */
	public BigDecimal getGold() {
		return gold;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.gold
	 * @param gold  the value for t_user.gold
	 * @mbg.generated  Thu Jul 29 19:06:14 CST 2021
	 */
	public void setGold(BigDecimal gold) {
		this.gold = gold;
	}
}