package com.anywide.shop.order.entity;

import java.math.BigDecimal;

public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_id
     *
     * @mbg.generated Mon Aug 02 17:01:17 CST 2021
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.product_id
     *
     * @mbg.generated Mon Aug 02 17:01:17 CST 2021
     */
    private Integer productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.user_id
     *
     * @mbg.generated Mon Aug 02 17:01:17 CST 2021
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.addtime
     *
     * @mbg.generated Mon Aug 02 17:01:17 CST 2021
     */
    private Integer addtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.amount
     *
     * @mbg.generated Mon Aug 02 17:01:17 CST 2021
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.status
     *
     * @mbg.generated Mon Aug 02 17:01:17 CST 2021
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.global_tx_id
     *
     * @mbg.generated Mon Aug 02 17:01:17 CST 2021
     */
    private String globalTxId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.branch_tx_id
     *
     * @mbg.generated Mon Aug 02 17:01:17 CST 2021
     */
    private String branchTxId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_id
     *
     * @return the value of t_order.order_id
     *
     * @mbg.generated Mon Aug 02 17:01:17 CST 2021
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_id
     *
     * @param orderId the value for t_order.order_id
     *
     * @mbg.generated Mon Aug 02 17:01:17 CST 2021
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.product_id
     *
     * @return the value of t_order.product_id
     *
     * @mbg.generated Mon Aug 02 17:01:17 CST 2021
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.product_id
     *
     * @param productId the value for t_order.product_id
     *
     * @mbg.generated Mon Aug 02 17:01:17 CST 2021
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.user_id
     *
     * @return the value of t_order.user_id
     *
     * @mbg.generated Mon Aug 02 17:01:17 CST 2021
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.user_id
     *
     * @param userId the value for t_order.user_id
     *
     * @mbg.generated Mon Aug 02 17:01:17 CST 2021
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.addtime
     *
     * @return the value of t_order.addtime
     *
     * @mbg.generated Mon Aug 02 17:01:17 CST 2021
     */
    public Integer getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.addtime
     *
     * @param addtime the value for t_order.addtime
     *
     * @mbg.generated Mon Aug 02 17:01:17 CST 2021
     */
    public void setAddtime(Integer addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.amount
     *
     * @return the value of t_order.amount
     *
     * @mbg.generated Mon Aug 02 17:01:17 CST 2021
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.amount
     *
     * @param amount the value for t_order.amount
     *
     * @mbg.generated Mon Aug 02 17:01:17 CST 2021
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.status
     *
     * @return the value of t_order.status
     *
     * @mbg.generated Mon Aug 02 17:01:17 CST 2021
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.status
     *
     * @param status the value for t_order.status
     *
     * @mbg.generated Mon Aug 02 17:01:17 CST 2021
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.global_tx_id
     *
     * @return the value of t_order.global_tx_id
     *
     * @mbg.generated Mon Aug 02 17:01:17 CST 2021
     */
    public String getGlobalTxId() {
        return globalTxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.global_tx_id
     *
     * @param globalTxId the value for t_order.global_tx_id
     *
     * @mbg.generated Mon Aug 02 17:01:17 CST 2021
     */
    public void setGlobalTxId(String globalTxId) {
        this.globalTxId = globalTxId == null ? null : globalTxId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.branch_tx_id
     *
     * @return the value of t_order.branch_tx_id
     *
     * @mbg.generated Mon Aug 02 17:01:17 CST 2021
     */
    public String getBranchTxId() {
        return branchTxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.branch_tx_id
     *
     * @param branchTxId the value for t_order.branch_tx_id
     *
     * @mbg.generated Mon Aug 02 17:01:17 CST 2021
     */
    public void setBranchTxId(String branchTxId) {
        this.branchTxId = branchTxId == null ? null : branchTxId.trim();
    }
}