package com.anywide.shop.user.mapper;

import com.anywide.shop.user.entity.GoldInfo;

public interface GoldInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_gold_info
     *
     * @mbg.generated Thu Jul 29 19:06:14 CST 2021
     */
    int deleteByPrimaryKey(Integer goldInfoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_gold_info
     *
     * @mbg.generated Thu Jul 29 19:06:14 CST 2021
     */
    int insert(GoldInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_gold_info
     *
     * @mbg.generated Thu Jul 29 19:06:14 CST 2021
     */
    int insertSelective(GoldInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_gold_info
     *
     * @mbg.generated Thu Jul 29 19:06:14 CST 2021
     */
    GoldInfo selectByPrimaryKey(Integer goldInfoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_gold_info
     *
     * @mbg.generated Thu Jul 29 19:06:14 CST 2021
     */
    int updateByPrimaryKeySelective(GoldInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_gold_info
     *
     * @mbg.generated Thu Jul 29 19:06:14 CST 2021
     */
    int updateByPrimaryKey(GoldInfo record);
    
    int confirmByBranchTxId(GoldInfo record);
    
    int cancelByBranchTxId(GoldInfo record);
    
    
}