package com.anywide.shop.product.entity;

public class ProductOperateInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product_operate_info.product_operate_id
     *
     * @mbg.generated Fri Jul 30 11:10:19 CST 2021
     */
    private Integer productOperateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product_operate_info.product_id
     *
     * @mbg.generated Fri Jul 30 11:10:19 CST 2021
     */
    private Integer productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product_operate_info.global_tx_id
     *
     * @mbg.generated Fri Jul 30 11:10:19 CST 2021
     */
    private String globalTxId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product_operate_info.branch_tx_id
     *
     * @mbg.generated Fri Jul 30 11:10:19 CST 2021
     */
    private String branchTxId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product_operate_info.status
     *
     * @mbg.generated Fri Jul 30 11:10:19 CST 2021
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product_operate_info.addtime
     *
     * @mbg.generated Fri Jul 30 11:10:19 CST 2021
     */
    private Integer addtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product_operate_info.stock
     *
     * @mbg.generated Fri Jul 30 11:10:19 CST 2021
     */
    private Integer stock;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product_operate_info.product_operate_id
     *
     * @return the value of t_product_operate_info.product_operate_id
     *
     * @mbg.generated Fri Jul 30 11:10:19 CST 2021
     */
    public Integer getProductOperateId() {
        return productOperateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product_operate_info.product_operate_id
     *
     * @param productOperateId the value for t_product_operate_info.product_operate_id
     *
     * @mbg.generated Fri Jul 30 11:10:19 CST 2021
     */
    public void setProductOperateId(Integer productOperateId) {
        this.productOperateId = productOperateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product_operate_info.product_id
     *
     * @return the value of t_product_operate_info.product_id
     *
     * @mbg.generated Fri Jul 30 11:10:19 CST 2021
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product_operate_info.product_id
     *
     * @param productId the value for t_product_operate_info.product_id
     *
     * @mbg.generated Fri Jul 30 11:10:19 CST 2021
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product_operate_info.global_tx_id
     *
     * @return the value of t_product_operate_info.global_tx_id
     *
     * @mbg.generated Fri Jul 30 11:10:19 CST 2021
     */
    public String getGlobalTxId() {
        return globalTxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product_operate_info.global_tx_id
     *
     * @param globalTxId the value for t_product_operate_info.global_tx_id
     *
     * @mbg.generated Fri Jul 30 11:10:19 CST 2021
     */
    public void setGlobalTxId(String globalTxId) {
        this.globalTxId = globalTxId == null ? null : globalTxId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product_operate_info.branch_tx_id
     *
     * @return the value of t_product_operate_info.branch_tx_id
     *
     * @mbg.generated Fri Jul 30 11:10:19 CST 2021
     */
    public String getBranchTxId() {
        return branchTxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product_operate_info.branch_tx_id
     *
     * @param branchTxId the value for t_product_operate_info.branch_tx_id
     *
     * @mbg.generated Fri Jul 30 11:10:19 CST 2021
     */
    public void setBranchTxId(String branchTxId) {
        this.branchTxId = branchTxId == null ? null : branchTxId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product_operate_info.status
     *
     * @return the value of t_product_operate_info.status
     *
     * @mbg.generated Fri Jul 30 11:10:19 CST 2021
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product_operate_info.status
     *
     * @param status the value for t_product_operate_info.status
     *
     * @mbg.generated Fri Jul 30 11:10:19 CST 2021
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product_operate_info.addtime
     *
     * @return the value of t_product_operate_info.addtime
     *
     * @mbg.generated Fri Jul 30 11:10:19 CST 2021
     */
    public Integer getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product_operate_info.addtime
     *
     * @param addtime the value for t_product_operate_info.addtime
     *
     * @mbg.generated Fri Jul 30 11:10:19 CST 2021
     */
    public void setAddtime(Integer addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product_operate_info.stock
     *
     * @return the value of t_product_operate_info.stock
     *
     * @mbg.generated Fri Jul 30 11:10:19 CST 2021
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product_operate_info.stock
     *
     * @param stock the value for t_product_operate_info.stock
     *
     * @mbg.generated Fri Jul 30 11:10:19 CST 2021
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }
}