package com.anywide.shop.product.mapper;

import com.anywide.shop.product.entity.ProductOperateInfo;

public interface ProductOperateInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_operate_info
     *
     * @mbg.generated Fri Jul 30 11:10:19 CST 2021
     */
    int deleteByPrimaryKey(Integer productOperateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_operate_info
     *
     * @mbg.generated Fri Jul 30 11:10:19 CST 2021
     */
    int insert(ProductOperateInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_operate_info
     *
     * @mbg.generated Fri Jul 30 11:10:19 CST 2021
     */
    int insertSelective(ProductOperateInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_operate_info
     *
     * @mbg.generated Fri Jul 30 11:10:19 CST 2021
     */
    ProductOperateInfo selectByPrimaryKey(Integer productOperateId);
 
    int updateByPrimaryKeySelective(ProductOperateInfo record);

    int updateByPrimaryKey(ProductOperateInfo record);
    
    int confirmByBranchTxId(ProductOperateInfo record);
    
    int cancelByBranchTxId(ProductOperateInfo record);
    
}